// ─────────────────────────────────────────────────────────────────────────────
// ReForm — Routines Data
// ─────────────────────────────────────────────────────────────────────────────

export interface Pose {
  id: string;
  name: string;
  sanskrit?: string;
  duration: number; // seconds
  description: string;
  cue: string;
  breathCue?: string;
  image?: string;
}

export interface Goal {
  id: string;
  title: string;
  icon: string;
  tagline: string;
  colorFrom: string;
  colorTo: string;
  textColor: string;
  poses: Pose[];
}

export const goals: Goal[] = [
  {
    id: "stress",
    title: "Stress Management",
    icon: "🧘",
    tagline: "Release tension, calm the mind",
    colorFrom: "#5BB8B0",
    colorTo: "#5AA1B8",
    textColor: "#1E293B",
    poses: [
      {
        id: "box-breathing",
        name: "Box Breathing",
        duration: 60,
        description: "Seated breath control to activate the parasympathetic nervous system.",
        cue: "Sit tall. Inhale 4 counts, hold 4, exhale 4, hold 4.",
        breathCue: "4-4-4-4 box pattern",
      },
      {
        id: "childs-pose",
        name: "Child's Pose",
        sanskrit: "Balasana",
        duration: 60,
        description: "A gentle resting pose that releases the lower back and quiets the mind.",
        cue: "Kneel, fold forward, arms extended, forehead to mat.",
        breathCue: "Deep belly breaths into the back body",
      },
      {
        id: "cat-cow",
        name: "Cat-Cow",
        sanskrit: "Marjaryasana-Bitilasana",
        duration: 60,
        description: "Fluid spinal movement synced with breath to release tension.",
        cue: "On all fours — arch on inhale (cow), round on exhale (cat).",
        breathCue: "Let the breath drive the movement",
      },
      {
        id: "seated-forward-fold",
        name: "Seated Forward Fold",
        sanskrit: "Paschimottanasana",
        duration: 60,
        description: "Calms the nervous system and stretches the spine and hamstrings.",
        cue: "Legs extended, hinge forward from the hips, hold gently.",
        breathCue: "Exhale deeper into the fold",
      },
      {
        id: "savasana",
        name: "Final Relaxation",
        sanskrit: "Savasana",
        duration: 90,
        description: "Complete stillness to integrate the practice and signal rest.",
        cue: "Lie flat, arms slightly away from body, eyes closed.",
        breathCue: "Let the breath become natural",
      },
    ],
  },
  {
    id: "flexibility",
    title: "Flexibility",
    icon: "🤸",
    tagline: "Open your body, free your movement",
    colorFrom: "#5AB890",
    colorTo: "#5BB8B0",
    textColor: "#1E293B",
    poses: [
      {
        id: "standing-forward-fold",
        name: "Standing Forward Fold",
        sanskrit: "Uttanasana",
        duration: 60,
        description: "Lengthens the hamstrings and spine while calming the mind.",
        cue: "Feet hip-width, hinge forward, let the head hang heavy.",
        breathCue: "Breathe length into the spine",
      },
      {
        id: "low-lunge",
        name: "Low Lunge",
        sanskrit: "Anjaneyasana",
        duration: 60,
        description: "Deep hip flexor and quad stretch.",
        cue: "Step one foot forward, back knee down, sink the hips.",
        breathCue: "Inhale to lengthen, exhale to deepen",
      },
      {
        id: "pigeon-pose",
        name: "Pigeon Pose",
        sanskrit: "Eka Pada Rajakapotasana",
        duration: 90,
        description: "Intense hip opener that releases deep stored tension.",
        cue: "Front shin angled, back leg extended, fold forward.",
        breathCue: "Breathe into the hip crease",
      },
      {
        id: "lizard-pose",
        name: "Lizard Pose",
        sanskrit: "Utthan Pristhasana",
        duration: 60,
        description: "Opens hips, groin, and hip flexors simultaneously.",
        cue: "Front foot outside of hand, both hands on the ground.",
        breathCue: "Stay soft in the jaw and hips",
      },
      {
        id: "seated-twist",
        name: "Seated Spinal Twist",
        sanskrit: "Ardha Matsyendrasana",
        duration: 45,
        description: "Detoxifying twist that improves spinal mobility.",
        cue: "One leg extended, other crossed over, twist toward bent knee.",
        breathCue: "Inhale tall, exhale deeper into the twist",
      },
    ],
  },
  {
    id: "posture",
    title: "Posture",
    icon: "🏛️",
    tagline: "Stand tall, move with confidence",
    colorFrom: "#5AB870",
    colorTo: "#5AB890",
    textColor: "#1E293B",
    poses: [
      {
        id: "mountain-pose",
        name: "Mountain Pose",
        sanskrit: "Tadasana",
        duration: 45,
        description: "The foundational standing pose that builds postural awareness.",
        cue: "Feet together, body aligned, arms at sides, crown up.",
        breathCue: "Breathe through the full length of the spine",
      },
      {
        id: "cobra",
        name: "Cobra Pose",
        sanskrit: "Bhujangasana",
        duration: 45,
        description: "Strengthens the back and opens the chest.",
        cue: "Lie prone, hands under shoulders, press up gently.",
        breathCue: "Inhale to lift, exhale to soften",
      },
      {
        id: "locust",
        name: "Locust Pose",
        sanskrit: "Salabhasana",
        duration: 45,
        description: "Activates posterior chain — key for good posture.",
        cue: "Lie prone, lift chest and legs simultaneously.",
        breathCue: "Hold the breath briefly at the top",
      },
      {
        id: "bridge",
        name: "Bridge Pose",
        sanskrit: "Setu Bandhasana",
        duration: 60,
        description: "Opens the chest and strengthens the posterior chain.",
        cue: "Feet flat, push hips up, clasp hands under back.",
        breathCue: "Breathe into the chest",
      },
      {
        id: "threading-needle",
        name: "Threading the Needle",
        duration: 45,
        description: "Releases thoracic tension and shoulder tightness.",
        cue: "On all fours, slide one arm under the other, cheek to mat.",
        breathCue: "Breathe into the upper back",
      },
    ],
  },
  {
    id: "general-fitness",
    title: "General Fitness",
    icon: "💪",
    tagline: "Build strength from the inside out",
    colorFrom: "#5A84B8",
    colorTo: "#5AA1B8",
    textColor: "#1E293B",
    poses: [
      {
        id: "sun-salutation-a",
        name: "Sun Salutation A",
        sanskrit: "Surya Namaskar A",
        duration: 90,
        description: "A complete sequence that warms the entire body.",
        cue: "Flow through: mountain → forward fold → plank → cobra → downdog.",
        breathCue: "One breath per movement",
      },
      {
        id: "warrior-1",
        name: "Warrior I",
        sanskrit: "Virabhadrasana I",
        duration: 45,
        description: "Builds leg strength, opens the chest and hips.",
        cue: "Front knee over ankle, back foot angled 45°, arms overhead.",
        breathCue: "Ground down to rise up",
      },
      {
        id: "warrior-2",
        name: "Warrior II",
        sanskrit: "Virabhadrasana II",
        duration: 45,
        description: "Strengthens legs, opens hips and chest laterally.",
        cue: "Wide stance, front knee tracks over toes, arms wide.",
        breathCue: "Steady, warrior breath",
      },
      {
        id: "chair-pose",
        name: "Chair Pose",
        sanskrit: "Utkatasana",
        duration: 45,
        description: "Powerful quad and glute strengthener.",
        cue: "Feet together, sink hips back and down, arms overhead.",
        breathCue: "Breathe through the burn",
      },
      {
        id: "plank",
        name: "Plank Hold",
        duration: 45,
        description: "Full-body isometric strength builder.",
        cue: "Wrists under shoulders, body in one straight line.",
        breathCue: "Steady breath, engaged core",
      },
    ],
  },
  {
    id: "better-sleep",
    title: "Better Sleep",
    icon: "🌙",
    tagline: "Wind down, drift into deep rest",
    colorFrom: "#5BB8B0",
    colorTo: "#5A84B8",
    textColor: "#1E293B",
    poses: [
      {
        id: "legs-up-wall",
        name: "Legs Up the Wall",
        sanskrit: "Viparita Karani",
        duration: 120,
        description: "Restores circulation and signals the body to rest.",
        cue: "Lie on your back, legs resting vertically against the wall.",
        breathCue: "Long, slow exhales",
      },
      {
        id: "supine-twist",
        name: "Supine Twist",
        sanskrit: "Supta Matsyendrasana",
        duration: 60,
        description: "Releases the lower back and calms the nervous system.",
        cue: "Lie flat, draw one knee across the body, arms wide.",
        breathCue: "Exhale fully to release deeper",
      },
      {
        id: "happy-baby",
        name: "Happy Baby",
        sanskrit: "Ananda Balasana",
        duration: 60,
        description: "A playful hip opener that releases spinal tension.",
        cue: "On back, hold outer feet, knees wide toward armpits.",
        breathCue: "Breathe naturally, smile",
      },
      {
        id: "yin-butterfly",
        name: "Reclining Butterfly",
        sanskrit: "Supta Baddha Konasana",
        duration: 90,
        description: "Passive hip opener deeply calming before sleep.",
        cue: "Soles of feet together, knees wide, arms relaxed out.",
        breathCue: "Let the body sink with each exhale",
      },
      {
        id: "4-7-8-breath",
        name: "4-7-8 Breathing",
        duration: 90,
        description: "A powerful sleep-inducing breathing technique.",
        cue: "Inhale 4 counts, hold 7, exhale 8 through the mouth.",
        breathCue: "4 in · 7 hold · 8 out",
      },
    ],
  },
  {
    id: "relaxation",
    title: "Relaxation",
    icon: "☁️",
    tagline: "Soften, surrender, restore",
    colorFrom: "#5AA1B8",
    colorTo: "#5BB8B0",
    textColor: "#1E293B",
    poses: [
      {
        id: "seated-meditation",
        name: "Centering Meditation",
        duration: 60,
        description: "Bring awareness inward and settle the mind.",
        cue: "Sit comfortably, close eyes, observe the natural breath.",
        breathCue: "Notice each breath without controlling it",
      },
      {
        id: "melting-heart",
        name: "Melting Heart",
        sanskrit: "Anahatasana",
        duration: 60,
        description: "Chest and shoulder opener with deep surrender.",
        cue: "Kneel, walk hands forward, chest toward the floor, hips above knees.",
        breathCue: "Exhale the chest closer to the mat",
      },
      {
        id: "supine-pigeon",
        name: "Supine Pigeon",
        duration: 60,
        description: "Figure-4 hip release in a gentle, reclined position.",
        cue: "On back, cross ankle over thigh, flex foot, pull legs in.",
        breathCue: "Breathe into the outer hip",
      },
      {
        id: "yin-sphinx",
        name: "Sphinx Pose",
        sanskrit: "Salamba Bhujangasana",
        duration: 90,
        description: "Gentle backbend stimulating the sacral-lumbar arch.",
        cue: "Lie prone, forearms on ground, press chest forward gently.",
        breathCue: "Breathe into the belly",
      },
      {
        id: "yoga-nidra-savasana",
        name: "Yoga Nidra Rest",
        duration: 120,
        description: "Guided body scan relaxation — the deepest rest.",
        cue: "Lie flat, eyes closed, scan and release each body part.",
        breathCue: "No effort — simply rest and observe",
      },
    ],
  },
  {
    id: "weight-management",
    title: "Weight Management",
    icon: "⚖️",
    tagline: "Energize, strengthen, and metabolize",
    colorFrom: "#5AB890",
    colorTo: "#5AB870",
    textColor: "#1E293B",
    poses: [
      {
        id: "sun-b",
        name: "Sun Salutation B",
        sanskrit: "Surya Namaskar B",
        duration: 90,
        description: "High-intensity flow that builds heat and burns calories.",
        cue: "Chair → forward fold → chaturanga → updog → downdog → warrior I.",
        breathCue: "Ujjayi breath — ocean-sounding",
      },
      {
        id: "boat-pose",
        name: "Boat Pose",
        sanskrit: "Navasana",
        duration: 45,
        description: "Core igniter that stimulates digestion.",
        cue: "Seated, lift legs to 45°, extend arms parallel to floor.",
        breathCue: "Breathe steadily — don't hold!",
      },
      {
        id: "twisted-chair",
        name: "Twisted Chair",
        sanskrit: "Parivrtta Utkatasana",
        duration: 45,
        description: "Detoxifying twist with core and leg strengthening.",
        cue: "Chair pose, then twist — elbow to outer knee, palms together.",
        breathCue: "Inhale to lengthen, exhale to twist",
      },
      {
        id: "side-plank",
        name: "Side Plank",
        sanskrit: "Vasisthasana",
        duration: 45,
        description: "Lateral stability, oblique strength, and balance.",
        cue: "Stack feet or stagger, one hand supports, other arm extended.",
        breathCue: "Steady breath — feel your strength",
      },
      {
        id: "camel-pose",
        name: "Camel Pose",
        sanskrit: "Ustrasana",
        duration: 45,
        description: "Deep heart opener that boosts energy and metabolism.",
        cue: "Kneel, press hips forward, reach back to heels.",
        breathCue: "Lift the heart on every inhale",
      },
    ],
  },
  {
    id: "back-neck",
    title: "Back/Neck Relief",
    icon: "🫁",
    tagline: "Decompress, release, realign",
    colorFrom: "#5AB870",
    colorTo: "#5BB8B0",
    textColor: "#1E293B",
    poses: [
      {
        id: "neck-rolls",
        name: "Neck Rolls",
        duration: 45,
        description: "Releases tension held in the neck and upper traps.",
        cue: "Chin to chest, slowly roll right, back, left. Reverse.",
        breathCue: "Exhale as the neck drops to each side",
      },
      {
        id: "cat-cow-neck",
        name: "Cat-Cow with Neck",
        duration: 60,
        description: "Spinal mobilization including cervical spine.",
        cue: "Include nod: chin to chest on cat, crown back on cow.",
        breathCue: "Let the breath guide the wave",
      },
      {
        id: "thread-needle-deep",
        name: "Threading the Needle",
        duration: 60,
        description: "Releases thoracic and cervical spinal tension.",
        cue: "On all fours, slide one arm under the other, ear to mat.",
        breathCue: "Breathe into the trapped shoulder",
      },
      {
        id: "supported-fish",
        name: "Supported Fish",
        sanskrit: "Matsyasana",
        duration: 90,
        description: "Opens the chest, relieves upper back compression.",
        cue: "Lie on a rolled blanket between shoulder blades, arms wide.",
        breathCue: "Breathe into the collarbones",
      },
      {
        id: "constructive-rest",
        name: "Constructive Rest",
        duration: 120,
        description: "Gravity-assisted spinal decompression — the gold standard.",
        cue: "Lie on back, knees bent, feet flat, arms on belly.",
        breathCue: "Exhale, let the spine lengthen into the floor",
      },
    ],
  },
  {
    id: "menstrual",
    title: "Menstrual Wellness",
    icon: "🌸",
    tagline: "Nurture your cycle, ease discomfort",
    colorFrom: "#5A84B8",
    colorTo: "#5AB890",
    textColor: "#1E293B",
    poses: [
      {
        id: "childs-pose-wide",
        name: "Wide Child's Pose",
        sanskrit: "Balasana",
        duration: 90,
        description: "Relieves cramps and lower back ache, calms the nervous system.",
        cue: "Knees wide, big toes touch, fold forward, arms extended.",
        breathCue: "Breathe into the lower belly",
      },
      {
        id: "butterfly",
        name: "Butterfly Pose",
        sanskrit: "Baddha Konasana",
        duration: 90,
        description: "Opens the hips and groin, eases pelvic tension.",
        cue: "Seated, soles together, fold forward gently.",
        breathCue: "Long exhales to release the groin",
      },
      {
        id: "reclined-butterfly",
        name: "Reclined Butterfly",
        duration: 90,
        description: "Passive hip opener — deeply supportive during menstruation.",
        cue: "Lie back, soles together, arms relaxed, bolster optional.",
        breathCue: "Soften the belly completely",
      },
      {
        id: "supta-twist-gentle",
        name: "Gentle Supine Twist",
        duration: 60,
        description: "Eases lower back tension and massages the internal organs.",
        cue: "Knees together, roll slowly to one side, hold gently.",
        breathCue: "No force — only ease",
      },
      {
        id: "warm-savasana",
        name: "Warm Savasana",
        duration: 120,
        description: "Restorative rest with a blanket over the lower belly.",
        cue: "Lie flat with warmth over the belly, total release.",
        breathCue: "You are held. Let go completely.",
      },
    ],
  },
  {
    id: "pcos",
    title: "PCOS Wellness",
    icon: "🌿",
    tagline: "Balance hormones, restore harmony",
    colorFrom: "#5BB8B0",
    colorTo: "#5AB870",
    textColor: "#1E293B",
    poses: [
      {
        id: "diaphragmatic-breath",
        name: "Diaphragmatic Breathing",
        duration: 60,
        description: "Activates the vagus nerve to balance cortisol and hormones.",
        cue: "Hand on belly, breathe so the belly rises and falls.",
        breathCue: "Slow 4-count inhale, 6-count exhale",
      },
      {
        id: "bound-angle",
        name: "Bound Angle Flow",
        sanskrit: "Baddha Konasana",
        duration: 90,
        description: "Stimulates pelvic organs and improves blood flow.",
        cue: "Soles together, flap knees gently like butterfly wings.",
        breathCue: "Exhale as knees lower",
      },
      {
        id: "warrior-2-pcos",
        name: "Warrior II",
        duration: 60,
        description: "Builds insulin sensitivity through large muscle activation.",
        cue: "Wide stance, front knee bends, arms spread wide, gaze forward.",
        breathCue: "Strong, steady breath — you are powerful",
      },
      {
        id: "bridge-pcos",
        name: "Bridge Pose",
        duration: 60,
        description: "Stimulates the thyroid, strengthens the pelvic floor.",
        cue: "Feet flat, lift hips, engage glutes, hold and breathe.",
        breathCue: "Breathe into the chest",
      },
      {
        id: "legs-up-pcos",
        name: "Legs Up the Wall",
        duration: 120,
        description: "Restores venous return, calms adrenal stress.",
        cue: "Lie near wall, legs rest vertically, arms out.",
        breathCue: "Breathe slowly — let the body reset",
      },
    ],
  },
];

export function getGoalById(id: string): Goal | undefined {
  return goals.find((g) => g.id === id);
}

export function getTotalDuration(poses: Pose[]): number {
  return poses.reduce((acc, p) => acc + p.duration, 0);
}
